-- MySQL Script generated by MySQL Workbench
-- Sat 22 Apr 2017 11:11:09 PM PKT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `PortfolioType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortfolioType` ;

CREATE TABLE IF NOT EXISTS `PortfolioType` (
  `portfolioTypeid` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`portfolioTypeid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ResourceType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ResourceType` ;

CREATE TABLE IF NOT EXISTS `ResourceType` (
  `resourceTypeid` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`resourceTypeid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Resource` ;

CREATE TABLE IF NOT EXISTS `Resource` (
  `resourceid` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `ResourceTypeid` INT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`resourceid`),
  INDEX `fk_Resource_ResourceType1_idx` (`ResourceTypeid` ASC),
  CONSTRAINT `fk_Resource_ResourceType1`
    FOREIGN KEY (`ResourceTypeid`)
    REFERENCES `ResourceType` (`resourceTypeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Team` ;

CREATE TABLE IF NOT EXISTS `Team` (
  `teamid` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`teamid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portfolio` ;

CREATE TABLE IF NOT EXISTS `Portfolio` (
  `portfolioid` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL COMMENT '	',
  `portfolioTypeid` INT NOT NULL,
  `owner` INT NOT NULL,
  `teamid` INT NOT NULL,
  `details` TEXT NULL,
  INDEX `fk_portfolios_portfolioType_idx` (`portfolioTypeid` ASC),
  INDEX `fk_portfolios_Resources1_idx` (`owner` ASC),
  INDEX `fk_portfolios_team1_idx` (`teamid` ASC),
  PRIMARY KEY (`portfolioid`),
  CONSTRAINT `fk_portfolios_portfolioType`
    FOREIGN KEY (`portfolioTypeid`)
    REFERENCES `PortfolioType` (`portfolioTypeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_portfolios_Resources1`
    FOREIGN KEY (`owner`)
    REFERENCES `Resource` (`resourceid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_portfolios_team1`
    FOREIGN KEY (`teamid`)
    REFERENCES `Team` (`teamid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeamResource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TeamResource` ;

CREATE TABLE IF NOT EXISTS `TeamResource` (
  `resourceid` INT NOT NULL,
  `teamid` INT NOT NULL,
  INDEX `fk_teamResources_Resources1_idx` (`resourceid` ASC),
  INDEX `fk_teamResources_team1_idx` (`teamid` ASC),
  PRIMARY KEY (`resourceid`),
  CONSTRAINT `fk_teamResources_Resources1`
    FOREIGN KEY (`resourceid`)
    REFERENCES `Resource` (`resourceid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teamResources_team1`
    FOREIGN KEY (`teamid`)
    REFERENCES `Team` (`teamid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserStory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UserStory` ;

CREATE TABLE IF NOT EXISTS `UserStory` (
  `userStoryid` INT NOT NULL AUTO_INCREMENT,
  `portfolioid` INT NOT NULL,
  `details` VARCHAR(100) NULL,
  `userResourceid` INT NOT NULL,
  PRIMARY KEY (`userStoryid`),
  INDEX `fk_UserStory_Portfolio1_idx` (`portfolioid` ASC),
  INDEX `fk_UserStory_Resource1_idx` (`userResourceid` ASC),
  CONSTRAINT `fk_UserStory_Portfolio1`
    FOREIGN KEY (`portfolioid`)
    REFERENCES `Portfolio` (`portfolioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserStory_Resource1`
    FOREIGN KEY (`userResourceid`)
    REFERENCES `Resource` (`resourceid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaskStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskStatus` ;

CREATE TABLE IF NOT EXISTS `TaskStatus` (
  `taskStatusid` INT NOT NULL,
  `title` VARCHAR(100) NULL,
  PRIMARY KEY (`taskStatusid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgressRatio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgressRatio` ;

CREATE TABLE IF NOT EXISTS `ProgressRatio` (
  `progressRatioid` INT NOT NULL,
  `descriptions` VARCHAR(100) NULL,
  PRIMARY KEY (`progressRatioid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Task` ;

CREATE TABLE IF NOT EXISTS `Task` (
  `taskid` BIGINT NOT NULL AUTO_INCREMENT,
  `userStoryid` INT NULL,
  `Resourceid` INT NULL,
  `estmatedStart` DATE NULL,
  `estimatedDuration` INT NULL,
  `actualStart` DATE NULL,
  `actualDuration` INT NULL,
  `taskStatusid` INT NULL,
  `progressRatioid` INT NOT NULL DEFAULT 0,
  `nextTaskId` BIGINT NULL,
  `previousTaskId` BIGINT NULL,
  PRIMARY KEY (`taskid`),
  INDEX `fk_Task_UserStory1_idx` (`userStoryid` ASC),
  INDEX `fk_Task_TeamResource1_idx` (`Resourceid` ASC),
  INDEX `fk_Task_TaskStatus1_idx` (`taskStatusid` ASC),
  INDEX `fk_Task_ProgressRatio1_idx` (`progressRatioid` ASC),
  INDEX `fk_Task_Task1_idx` (`nextTaskId` ASC),
  INDEX `fk_Task_Task2_idx` (`previousTaskId` ASC),
  CONSTRAINT `fk_Task_UserStory1`
    FOREIGN KEY (`userStoryid`)
    REFERENCES `UserStory` (`userStoryid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_TeamResource1`
    FOREIGN KEY (`Resourceid`)
    REFERENCES `TeamResource` (`resourceid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_TaskStatus1`
    FOREIGN KEY (`taskStatusid`)
    REFERENCES `TaskStatus` (`taskStatusid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_ProgressRatio1`
    FOREIGN KEY (`progressRatioid`)
    REFERENCES `ProgressRatio` (`progressRatioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_Task1`
    FOREIGN KEY (`nextTaskId`)
    REFERENCES `Task` (`taskid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_Task2`
    FOREIGN KEY (`previousTaskId`)
    REFERENCES `Task` (`taskid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkLog` ;

CREATE TABLE IF NOT EXISTS `WorkLog` (
  `workLogid` INT NOT NULL,
  `startTime` VARCHAR(100) NULL,
  `endTime` VARCHAR(100) NULL,
  `Duration` VARCHAR(100) NULL,
  `taskid` BIGINT NOT NULL,
  PRIMARY KEY (`workLogid`),
  INDEX `fk_WorkLog_Task1_idx` (`taskid` ASC),
  CONSTRAINT `fk_WorkLog_Task1`
    FOREIGN KEY (`taskid`)
    REFERENCES `Task` (`taskid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaskLinksLabel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskLinksLabel` ;

CREATE TABLE IF NOT EXISTS `TaskLinksLabel` (
  `taskLinksLabelid` INT NOT NULL,
  `label` VARCHAR(100) NULL,
  PRIMARY KEY (`taskLinksLabelid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `externalLInks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `externalLInks` ;

CREATE TABLE IF NOT EXISTS `externalLInks` (
  `externalLInksid` INT NOT NULL,
  `url` VARCHAR(100) NULL,
  `taskid` BIGINT NOT NULL,
  `linksLabelid` INT NOT NULL,
  PRIMARY KEY (`externalLInksid`),
  INDEX `fk_externalLInks_Task1_idx` (`taskid` ASC),
  INDEX `fk_externalLInks_LinksLabel1_idx` (`linksLabelid` ASC),
  CONSTRAINT `fk_externalLInks_Task1`
    FOREIGN KEY (`taskid`)
    REFERENCES `Task` (`taskid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_externalLInks_LinksLabel1`
    FOREIGN KEY (`linksLabelid`)
    REFERENCES `TaskLinksLabel` (`taskLinksLabelid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortFoliLables`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortFoliLables` ;

CREATE TABLE IF NOT EXISTS `PortFoliLables` (
  `portFoliLablesid` INT NOT NULL,
  `label` VARCHAR(100) NULL,
  `portfolioid` INT NOT NULL,
  PRIMARY KEY (`portFoliLablesid`),
  INDEX `fk_PortFoliLables_Portfolio1_idx` (`portfolioid` ASC),
  CONSTRAINT `fk_PortFoliLables_Portfolio1`
    FOREIGN KEY (`portfolioid`)
    REFERENCES `Portfolio` (`portfolioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dictionary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dictionary` ;

CREATE TABLE IF NOT EXISTS `Dictionary` (
  `Key` VARCHAR(100) NOT NULL,
  `shortTitle` VARCHAR(100) NULL,
  `LongTitle` VARCHAR(100) NULL,
  `ContextHelp` VARCHAR(100) NULL,
  PRIMARY KEY (`Key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortFoliLinksLabel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortFoliLinksLabel` ;

CREATE TABLE IF NOT EXISTS `PortFoliLinksLabel` (
  `portFoliLinksLabelid` INT NOT NULL,
  `label` VARCHAR(100) NULL,
  `Url` VARCHAR(100) NULL,
  PRIMARY KEY (`portFoliLinksLabelid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortFoliLinks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortFoliLinks` ;

CREATE TABLE IF NOT EXISTS `PortFoliLinks` (
  `portFoliLinksid` INT NOT NULL,
  `portFoliLinksLabelid` INT NOT NULL,
  `portfolioid` INT NOT NULL,
  PRIMARY KEY (`portFoliLinksid`),
  INDEX `fk_PortFoliLinks_PortFoliLinksLabel1_idx` (`portFoliLinksLabelid` ASC),
  INDEX `fk_PortFoliLinks_Portfolio1_idx` (`portfolioid` ASC),
  CONSTRAINT `fk_PortFoliLinks_PortFoliLinksLabel1`
    FOREIGN KEY (`portFoliLinksLabelid`)
    REFERENCES `PortFoliLinksLabel` (`portFoliLinksLabelid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PortFoliLinks_Portfolio1`
    FOREIGN KEY (`portfolioid`)
    REFERENCES `Portfolio` (`portfolioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
