-- MySQL Script generated by MySQL Workbench
-- Mon 05 Jun 2017 02:05:23 PM PKT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema gameplan2
-- -----------------------------------------------------
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PortfolioType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortfolioType` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PortfolioType` (
  `portfolioTypeid` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`portfolioTypeid`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PortfolioStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortfolioStatus` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PortfolioStatus` (
  `portfoliostatusid` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  PRIMARY KEY (`portfoliostatusid`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Team` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Team` (
  `teamid` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`teamid`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ResourceType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ResourceType` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ResourceType` (
  `resourceTypeid` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`resourceTypeid`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Resource` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Resource` (
  `resourceid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `teamid` INT NOT NULL,
  `resourceTypeid` INT NOT NULL,
  PRIMARY KEY (`resourceid`),
  CONSTRAINT `fk_Resource_Team1`
    FOREIGN KEY (`teamid`)
    REFERENCES `Team` (`teamid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resource_ResourceType1`
    FOREIGN KEY (`resourceTypeid`)
    REFERENCES `ResourceType` (`resourceTypeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Portfolio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portfolio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Portfolio` (
  `portfolioid` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL COMMENT '	',
  `portfolioTypeid` INT NOT NULL,
  `details` TEXT NULL,
  `rank` BIGINT NOT NULL DEFAULT 1,
  `portfoliostatusid` INT NOT NULL,
  `owner` INT NOT NULL,
  `createDate` DATE NULL,
  `createby` VARCHAR(100) NULL,
  `updatedate` DATE NULL,
  `updateby` VARCHAR(100) NULL,
  PRIMARY KEY (`portfolioid`, `owner`),
  CONSTRAINT `fk_portfolios_portfolioType`
    FOREIGN KEY (`portfolioTypeid`)
    REFERENCES `PortfolioType` (`portfolioTypeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Portfolio_PortfolioStatus1`
    FOREIGN KEY (`portfoliostatusid`)
    REFERENCES `PortfolioStatus` (`portfoliostatusid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Portfolio_Resource1`
    FOREIGN KEY (`owner`)
    REFERENCES `Resource` (`resourceid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ReleaseStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ReleaseStatus` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ReleaseStatus` (
  `releasestatusid` INT NOT NULL,
  `title` VARCHAR(100) NULL,
  PRIMARY KEY (`releasestatusid`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `portfolioReleases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolioReleases` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `portfolioReleases` (
  `portfolioid` INT NOT NULL,
  `releaseId` INT NOT NULL AUTO_INCREMENT,
  `planStartDate` DATE NULL,
  `actualStartDate` DATE NULL,
  `teamid` INT NOT NULL,
  `planEndDate` DATE NULL,
  `actualEndDate` DATE NULL,
  `details` VARCHAR(100) NULL DEFAULT ' ',
  `releasestatusid` INT NOT NULL,
  `createDate` DATE NULL,
  `createby` VARCHAR(100) NULL,
  `updatedate` DATE NULL,
  `updateby` VARCHAR(100) NULL,
  PRIMARY KEY (`releaseId`),
  CONSTRAINT `fk_portfoliReleases_Team1`
    FOREIGN KEY (`teamid`)
    REFERENCES `Team` (`teamid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_portfolioReleases_ReleaseStatus1`
    FOREIGN KEY (`releasestatusid`)
    REFERENCES `ReleaseStatus` (`releasestatusid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sprint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sprint` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sprint` (
  `sprintid` INT NOT NULL AUTO_INCREMENT,
  `details` VARCHAR(100) NULL,
  `startDate` DATE NULL,
  `End` DATE NULL,
  `releaseId` INT NOT NULL,
  `createDate` DATE NULL,
  `createby` VARCHAR(100) NULL,
  `updateby` VARCHAR(100) NULL,
  `updatedate` DATE NULL,
  PRIMARY KEY (`sprintid`),
  CONSTRAINT `fk_Sprint_portfolioReleases1`
    FOREIGN KEY (`releaseId`)
    REFERENCES `portfolioReleases` (`releaseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `UserStory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UserStory` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `UserStory` (
  `userStoryid` INT NOT NULL AUTO_INCREMENT,
  `details` VARCHAR(100) NULL,
  `sprintid` INT NULL,
  `releaseId` INT NOT NULL,
  `createby` VARCHAR(100) NULL,
  `createDate` DATE NULL,
  `updateby` VARCHAR(100) NULL,
  `updatedate` DATE NULL,
  PRIMARY KEY (`userStoryid`),
  CONSTRAINT `fk_UserStory_Sprint1`
    FOREIGN KEY (`sprintid`)
    REFERENCES `sprint` (`sprintid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserStory_portfolioReleases1`
    FOREIGN KEY (`releaseId`)
    REFERENCES `portfolioReleases` (`releaseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TaskStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskStatus` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TaskStatus` (
  `taskStatusid` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  PRIMARY KEY (`taskStatusid`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ProgressRatio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgressRatio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ProgressRatio` (
  `progressRatioid` INT NOT NULL AUTO_INCREMENT,
  `descriptions` VARCHAR(100) NULL,
  PRIMARY KEY (`progressRatioid`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Task` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Task` (
  `taskid` BIGINT NOT NULL AUTO_INCREMENT,
  `userStoryid` INT NULL,
  `estmatedStart` DATE NULL,
  `estimatedDuration` INT NULL,
  `actualStart` DATE NULL,
  `actualDuration` INT NULL,
  `taskStatusid` INT NULL,
  `progressRatioid` INT NOT NULL DEFAULT 0,
  `nextTaskId` BIGINT NULL,
  `previousTaskId` BIGINT NULL,
  `resourceid` INT NOT NULL,
  PRIMARY KEY (`taskid`),
  CONSTRAINT `fk_Task_UserStory1`
    FOREIGN KEY (`userStoryid`)
    REFERENCES `UserStory` (`userStoryid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_TaskStatus1`
    FOREIGN KEY (`taskStatusid`)
    REFERENCES `TaskStatus` (`taskStatusid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_ProgressRatio1`
    FOREIGN KEY (`progressRatioid`)
    REFERENCES `ProgressRatio` (`progressRatioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_Resource1`
    FOREIGN KEY (`resourceid`)
    REFERENCES `Resource` (`resourceid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `WorkLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkLog` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `WorkLog` (
  `workLogid` INT NOT NULL AUTO_INCREMENT,
  `startTime` VARCHAR(100) NULL,
  `endTime` VARCHAR(100) NULL,
  `Duration` VARCHAR(100) NULL,
  `taskid` BIGINT NOT NULL,
  PRIMARY KEY (`workLogid`),
  CONSTRAINT `fk_WorkLog_Task1`
    FOREIGN KEY (`taskid`)
    REFERENCES `Task` (`taskid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TaskLinksLabel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskLinksLabel` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TaskLinksLabel` (
  `taskLinksLabelid` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(100) NULL,
  PRIMARY KEY (`taskLinksLabelid`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `externalLInks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `externalLInks` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `externalLInks` (
  `externalLInksid` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(100) NULL,
  `taskid` BIGINT NOT NULL,
  `linksLabelid` INT NOT NULL,
  PRIMARY KEY (`externalLInksid`),
  CONSTRAINT `fk_externalLInks_Task1`
    FOREIGN KEY (`taskid`)
    REFERENCES `Task` (`taskid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_externalLInks_LinksLabel1`
    FOREIGN KEY (`linksLabelid`)
    REFERENCES `TaskLinksLabel` (`taskLinksLabelid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PortFoliLables`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortFoliLables` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PortFoliLables` (
  `portFoliLablesid` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(100) NULL,
  `portfolioid` INT NOT NULL,
  PRIMARY KEY (`portFoliLablesid`),
  CONSTRAINT `fk_PortFoliLables_Portfolio1`
    FOREIGN KEY (`portfolioid`)
    REFERENCES `Portfolio` (`portfolioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Dictionary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dictionary` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Dictionary` (
  `Key` VARCHAR(100) NOT NULL,
  `shortTitle` VARCHAR(100) NULL,
  `LongTitle` VARCHAR(100) NULL,
  `ContextHelp` VARCHAR(100) NULL,
  PRIMARY KEY (`Key`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PortFoliLinksLabel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortFoliLinksLabel` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PortFoliLinksLabel` (
  `portFoliLinksLabelid` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(100) NULL,
  `Url` VARCHAR(100) NULL,
  PRIMARY KEY (`portFoliLinksLabelid`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PortfolioLInks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortfolioLInks` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PortfolioLInks` (
  `portFoliLinksid` INT NOT NULL AUTO_INCREMENT,
  `portfolioid` INT NOT NULL,
  `portFoliLinksLabelid` INT NOT NULL,
  PRIMARY KEY (`portFoliLinksid`),
  CONSTRAINT `fk_PortfolioLInks_Portfolio1`
    FOREIGN KEY (`portfolioid`)
    REFERENCES `Portfolio` (`portfolioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PortfolioLInks_PortFoliLinksLabel1`
    FOREIGN KEY (`portFoliLinksLabelid`)
    REFERENCES `PortFoliLinksLabel` (`portFoliLinksLabelid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `auth_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth_group` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `auth_group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name` ON `auth_group` (`name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `django_content_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `django_content_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `django_content_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE UNIQUE INDEX `django_content_type_app_label_6a46e76723f2a523_uniq` ON `django_content_type` (`app_label` ASC, `model` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `auth_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth_permission` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `auth_permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT(11) NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `auth__content_type_id_68a76d522108c380_fk_django_content_type_id`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 124
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `auth_group_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth_group_permissions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `auth_group_permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `auth_group_p_permission_id_bb6bfa952406395_fk_auth_permission_id`
    FOREIGN KEY (`permission_id`)
    REFERENCES `auth_permission` (`id`),
  CONSTRAINT `auth_group_permissions_group_id_b6891699b9e7a7f_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `auth_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth_user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `auth_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME(6) NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `date_joined` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE UNIQUE INDEX `username` ON `auth_user` (`username` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `auth_user_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth_user_groups` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `auth_user_groups` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `group_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `auth_user_groups_group_id_3ede0f9832725b08_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `auth_group` (`id`),
  CONSTRAINT `auth_user_groups_user_id_655dbca2ecd17c76_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `auth_user_user_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth_user_user_permissions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `auth_user_user_permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `auth_user_u_permission_id_1e5a97a696f6d4e2_fk_auth_permission_id`
    FOREIGN KEY (`permission_id`)
    REFERENCES `auth_permission` (`id`),
  CONSTRAINT `auth_user_user_permissi_user_id_67f1081c74f8067a_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dictionary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dictionary` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `dictionary` (
  `Key` VARCHAR(100) NOT NULL,
  `shortTitle` VARCHAR(100) NULL DEFAULT NULL,
  `LongTitle` VARCHAR(100) NULL DEFAULT NULL,
  `ContextHelp` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Key`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `django_admin_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `django_admin_log` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `django_admin_log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME(6) NOT NULL,
  `object_id` LONGTEXT NULL DEFAULT NULL,
  `object_repr` VARCHAR(200) NOT NULL,
  `action_flag` SMALLINT(5) UNSIGNED NOT NULL,
  `change_message` LONGTEXT NOT NULL,
  `content_type_id` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `django_admin_log_user_id_77279d384b22150a_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `auth_user` (`id`),
  CONSTRAINT `django_content_type_id_71a9cf6830b9f3b_fk_django_content_type_id`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `django_migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `django_migrations` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `django_migrations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `app` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `applied` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `django_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `django_session` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `django_session` (
  `session_key` VARCHAR(40) NOT NULL,
  `session_data` LONGTEXT NOT NULL,
  `expire_date` DATETIME(6) NOT NULL,
  PRIMARY KEY (`session_key`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `django_session_de54fa62` ON `django_session` (`expire_date` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tasklinkslabel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasklinkslabel` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tasklinkslabel` (
  `taskLinksLabelid` INT(11) NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`taskLinksLabelid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `progressratio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `progressratio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `progressratio` (
  `progressRatioid` INT(11) NOT NULL AUTO_INCREMENT,
  `descriptions` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`progressRatioid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `resourcetype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resourcetype` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `resourcetype` (
  `resourceTypeid` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`resourceTypeid`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team` (
  `teamid` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`teamid`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `resource` (
  `resourceid` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `active` TINYINT(4) NOT NULL DEFAULT '1',
  `teamid` INT(11) NOT NULL,
  `resourceTypeid` INT(11) NOT NULL,
  PRIMARY KEY (`resourceid`),
  CONSTRAINT `fk_Resource_ResourceType1`
    FOREIGN KEY (`resourceTypeid`)
    REFERENCES `resourcetype` (`resourceTypeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resource_Team1`
    FOREIGN KEY (`teamid`)
    REFERENCES `team` (`teamid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `taskstatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taskstatus` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `taskstatus` (
  `taskStatusid` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`taskStatusid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `task` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `task` (
  `taskid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `userStoryid` INT(11) NULL DEFAULT NULL,
  `estmatedStart` DATE NULL DEFAULT NULL,
  `estimatedDuration` INT(11) NULL DEFAULT NULL,
  `actualStart` DATE NULL DEFAULT NULL,
  `actualDuration` INT(11) NULL DEFAULT NULL,
  `taskStatusid` INT(11) NULL DEFAULT NULL,
  `progressRatioid` INT(11) NOT NULL DEFAULT '0',
  `nextTaskId` BIGINT(20) NULL DEFAULT NULL,
  `previousTaskId` BIGINT(20) NULL DEFAULT NULL,
  `resourceid` INT(11) NOT NULL,
  PRIMARY KEY (`taskid`),
  CONSTRAINT `fk_Task_ProgressRatio1`
    FOREIGN KEY (`progressRatioid`)
    REFERENCES `progressratio` (`progressRatioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_Resource1`
    FOREIGN KEY (`resourceid`)
    REFERENCES `resource` (`resourceid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_TaskStatus1`
    FOREIGN KEY (`taskStatusid`)
    REFERENCES `taskstatus` (`taskStatusid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_UserStory1`
    FOREIGN KEY (`userStoryid`)
    REFERENCES `userstory` (`userStoryid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `externallinks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `externallinks` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `externallinks` (
  `externalLInksid` INT(11) NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(100) NULL DEFAULT NULL,
  `taskid` BIGINT(20) NOT NULL,
  `linksLabelid` INT(11) NOT NULL,
  PRIMARY KEY (`externalLInksid`),
  CONSTRAINT `fk_externalLInks_LinksLabel1`
    FOREIGN KEY (`linksLabelid`)
    REFERENCES `tasklinkslabel` (`taskLinksLabelid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_externalLInks_Task1`
    FOREIGN KEY (`taskid`)
    REFERENCES `task` (`taskid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `portfolilables`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolilables` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `portfolilables` (
  `portFoliLablesid` INT(11) NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(100) NULL DEFAULT NULL,
  `portfolioid` INT(11) NOT NULL,
  PRIMARY KEY (`portFoliLablesid`),
  CONSTRAINT `fk_PortFoliLables_Portfolio1`
    FOREIGN KEY (`portfolioid`)
    REFERENCES `portfolio` (`portfolioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `portfolilinkslabel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolilinkslabel` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `portfolilinkslabel` (
  `portFoliLinksLabelid` INT(11) NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(100) NULL DEFAULT NULL,
  `Url` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`portFoliLinksLabelid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `portfoliolinks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfoliolinks` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `portfoliolinks` (
  `portFoliLinksid` INT(11) NOT NULL AUTO_INCREMENT,
  `portfolioid` INT(11) NOT NULL,
  `portFoliLinksLabelid` INT(11) NOT NULL,
  PRIMARY KEY (`portFoliLinksid`),
  CONSTRAINT `fk_PortfolioLInks_PortFoliLinksLabel1`
    FOREIGN KEY (`portFoliLinksLabelid`)
    REFERENCES `portfolilinkslabel` (`portFoliLinksLabelid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PortfolioLInks_Portfolio1`
    FOREIGN KEY (`portfolioid`)
    REFERENCES `portfolio` (`portfolioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `portfoliostatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfoliostatus` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `portfoliostatus` (
  `portfoliostatusid` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`portfoliostatusid`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `portfoliotype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfoliotype` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `portfoliotype` (
  `portfolioTypeid` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`portfolioTypeid`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `releasestatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `releasestatus` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `releasestatus` (
  `releasestatusid` INT(11) NOT NULL,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`releasestatusid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `scrum_sprint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scrum_sprint` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `scrum_sprint` (
  `sprintid` INT(11) NOT NULL AUTO_INCREMENT,
  `details` VARCHAR(100) NULL DEFAULT NULL,
  `startDate` DATE NULL DEFAULT NULL,
  `End` DATE NULL DEFAULT NULL,
  `releaseid` INT(11) NOT NULL,
  PRIMARY KEY (`sprintid`),
  CONSTRAINT `scrum_sprint_releaseid_ed650e2a_fk_portfolioReleases_releaseid`
    FOREIGN KEY (`releaseid`)
    REFERENCES `portfolioreleases` (`releaseId`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sprint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sprint` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sprint` (
  `sprintid` INT(11) NOT NULL AUTO_INCREMENT,
  `details` VARCHAR(100) NULL DEFAULT NULL,
  `startDate` DATE NULL DEFAULT NULL,
  `End` DATE NULL DEFAULT NULL,
  `releaseId` INT(11) NOT NULL,
  `updateby` VARCHAR(100) NULL DEFAULT NULL,
  `updatedate` DATE NULL DEFAULT NULL,
  `createdate` DATE NULL DEFAULT NULL,
  `createby` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`sprintid`),
  CONSTRAINT `fk_Sprint_portfolioReleases1`
    FOREIGN KEY (`releaseId`)
    REFERENCES `portfolioreleases` (`releaseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `teamresource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teamresource` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `teamresource` (
  `resourceid` INT(11) NOT NULL,
  `teamid` INT(11) NOT NULL,
  PRIMARY KEY (`resourceid`),
  CONSTRAINT `fk_TeamResource_Team1`
    FOREIGN KEY (`teamid`)
    REFERENCES `team` (`teamid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teamResources_Resources1`
    FOREIGN KEY (`resourceid`)
    REFERENCES `resource` (`resourceid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `worklog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worklog` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `worklog` (
  `workLogid` INT(11) NOT NULL AUTO_INCREMENT,
  `startTime` VARCHAR(100) NULL DEFAULT NULL,
  `endTime` VARCHAR(100) NULL DEFAULT NULL,
  `Duration` VARCHAR(100) NULL DEFAULT NULL,
  `taskid` BIGINT(20) NOT NULL,
  PRIMARY KEY (`workLogid`),
  CONSTRAINT `fk_WorkLog_Task1`
    FOREIGN KEY (`taskid`)
    REFERENCES `task` (`taskid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
