# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('key', models.CharField(db_column='Key', max_length=100, primary_key=True, serialize=False)),
                ('shorttitle', models.CharField(blank=True, db_column='shortTitle', max_length=100, null=True)),
                ('longtitle', models.CharField(blank=True, db_column='LongTitle', max_length=100, null=True)),
                ('contexthelp', models.CharField(blank=True, db_column='ContextHelp', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Dictionary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Externallinks',
            fields=[
                ('externallinksid', models.AutoField(db_column='externalLInksid', primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'externalLInks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolilables',
            fields=[
                ('portfolilablesid', models.AutoField(db_column='portFoliLablesid', primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'PortFoliLables',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolilinks',
            fields=[
                ('portfolilinksid', models.AutoField(db_column='portFoliLinksid', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PortFoliLinks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolilinkslabel',
            fields=[
                ('portfolilinkslabelid', models.AutoField(db_column='portFoliLinksLabelid', primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, db_column='Url', max_length=100, null=True)),
            ],
            options={
                'db_table': 'PortFoliLinksLabel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolioid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Portfolio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Portfoliolinks',
            fields=[
                ('portfolilinksid', models.AutoField(db_column='portFoliLinksid', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PortfolioLInks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Portfoliostatus',
            fields=[
                ('portfoliostatusid', models.AutoField(db_column='PortfolioStatusid', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=100, null=True)),
            ],
            options={
                'db_table': 'PortfolioStatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Portfoliotype',
            fields=[
                ('portfoliotypeid', models.AutoField(db_column='portfolioTypeid', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PortfolioType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolireleases',
            fields=[
                ('releaseid', models.IntegerField(db_column='releaseId', primary_key=True, serialize=False)),
                ('plandate', models.DateField(blank=True, db_column='planDate', null=True)),
                ('actualdate', models.DateField(blank=True, db_column='actualDate', null=True)),
            ],
            options={
                'db_table': 'portfoliReleases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Progressratio',
            fields=[
                ('progressratioid', models.AutoField(db_column='progressRatioid', primary_key=True, serialize=False)),
                ('descriptions', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ProgressRatio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resourceid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'Resource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resourcetype',
            fields=[
                ('resourcetypeid', models.AutoField(db_column='resourceTypeid', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ResourceType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskid', models.BigAutoField(primary_key=True, serialize=False)),
                ('estmatedstart', models.DateField(blank=True, db_column='estmatedStart', null=True)),
                ('estimatedduration', models.IntegerField(blank=True, db_column='estimatedDuration', null=True)),
                ('actualstart', models.DateField(blank=True, db_column='actualStart', null=True)),
                ('actualduration', models.IntegerField(blank=True, db_column='actualDuration', null=True)),
                ('nexttaskid', models.BigIntegerField(blank=True, db_column='nextTaskId', null=True)),
                ('previoustaskid', models.BigIntegerField(blank=True, db_column='previousTaskId', null=True)),
            ],
            options={
                'db_table': 'Task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasklinkslabel',
            fields=[
                ('tasklinkslabelid', models.AutoField(db_column='taskLinksLabelid', primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'TaskLinksLabel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taskstatus',
            fields=[
                ('taskstatusid', models.AutoField(db_column='taskStatusid', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'TaskStatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userstory',
            fields=[
                ('userstoryid', models.AutoField(db_column='userStoryid', primary_key=True, serialize=False)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'UserStory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Worklog',
            fields=[
                ('worklogid', models.AutoField(db_column='workLogid', primary_key=True, serialize=False)),
                ('starttime', models.CharField(blank=True, db_column='startTime', max_length=100, null=True)),
                ('endtime', models.CharField(blank=True, db_column='endTime', max_length=100, null=True)),
                ('duration', models.CharField(blank=True, db_column='Duration', max_length=100, null=True)),
            ],
            options={
                'db_table': 'WorkLog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teamresource',
            fields=[
                ('resourceid', models.ForeignKey(db_column='resourceid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='scrum.Resource')),
                ('teamid', models.ForeignKey(db_column='teamid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, to='scrum.Team')),
            ],
            options={
                'db_table': 'TeamResource',
                'managed': False,
            },
        ),
    ]
