# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 07:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('key', models.CharField(db_column='Key', max_length=100, primary_key=True, serialize=False)),
                ('shorttitle', models.CharField(blank=True, db_column='shortTitle', max_length=100, null=True)),
                ('longtitle', models.CharField(blank=True, db_column='LongTitle', max_length=100, null=True)),
                ('contexthelp', models.CharField(blank=True, db_column='ContextHelp', max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Dictionary',
            },
        ),
        migrations.CreateModel(
            name='ExternalLinks',
            fields=[
                ('externallinksid', models.AutoField(db_column='externallinksid', primary_key=True, serialize=False)),
                ('urltext', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'externalLInks',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolioid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField(db_column='rank', default=1)),
                ('createby', models.CharField(max_length=100)),
                ('createdate', models.DateField(blank=True, db_column='createDate', default=datetime.date.today, null=True)),
                ('updateby', models.CharField(max_length=100)),
                ('updatedate', models.DateField(blank=True, db_column='updatedate', default=datetime.date.today, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Portfolio',
            },
        ),
        migrations.CreateModel(
            name='Portfoliolables',
            fields=[
                ('portfoliolablesid', models.AutoField(db_column='portfolioLablesid', primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'PortfoliLables',
            },
        ),
        migrations.CreateModel(
            name='PortfolioLinks',
            fields=[
                ('portfolioLinksid', models.AutoField(db_column='portfolioLinksid', primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'PortfolioLinks',
            },
        ),
        migrations.CreateModel(
            name='PortfolioLinksLabel',
            fields=[
                ('portfolioLinkslabelid', models.AutoField(db_column='portfoliolinkslabelid', primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, db_column='Url', max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'portfoliolinkslabelid',
            },
        ),
        migrations.CreateModel(
            name='PortfolioReleases',
            fields=[
                ('releaseid', models.AutoField(db_column='releaseId', primary_key=True, serialize=False)),
                ('planstartdate', models.DateField(blank=True, db_column='planStartDate', null=True)),
                ('actualstartdate', models.DateField(blank=True, db_column='actualStartDate', null=True)),
                ('planenddate', models.DateField(blank=True, db_column='planEndDate', null=True)),
                ('actualenddate', models.DateField(blank=True, db_column='actualEndDate', null=True)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('createby', models.CharField(max_length=100)),
                ('createdate', models.DateField(blank=True, db_column='createDate', default=datetime.date.today, null=True)),
                ('updateby', models.CharField(max_length=100)),
                ('updatedate', models.DateField(blank=True, db_column='updatedate', default=datetime.date.today, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'portfolioReleases',
            },
        ),
        migrations.CreateModel(
            name='PortfolioStatus',
            fields=[
                ('portfoliostatusid', models.AutoField(db_column='PortfolioStatusid', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'PortfolioStatus',
            },
        ),
        migrations.CreateModel(
            name='PortfolioType',
            fields=[
                ('portfoliotypeid', models.AutoField(db_column='portfolioTypeid', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'PortfolioType',
            },
        ),
        migrations.CreateModel(
            name='ProgressRatio',
            fields=[
                ('progressratioid', models.AutoField(db_column='progressRatioid', primary_key=True, serialize=False)),
                ('descriptions', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ProgressRatio',
            },
        ),
        migrations.CreateModel(
            name='ReleaseStatus',
            fields=[
                ('releasestatusid', models.AutoField(db_column='releasestatusid', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='title', max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ReleaseStatus',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resourceid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('active', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'Resource',
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('resourcetypeid', models.AutoField(db_column='resourceTypeid', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ResourceType',
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('sprintid', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('startdate', models.DateField(blank=True, db_column='startDate', null=True)),
                ('enddate', models.DateField(blank=True, db_column='End', null=True)),
                ('createby', models.CharField(max_length=100)),
                ('createdate', models.DateField(blank=True, db_column='createDate', default=datetime.date.today, null=True)),
                ('updateby', models.CharField(max_length=100)),
                ('updatedate', models.DateField(blank=True, db_column='updatedate', default=datetime.date.today, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'sprint',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskid', models.BigAutoField(primary_key=True, serialize=False)),
                ('estmatedstart', models.DateField(blank=True, db_column='estmatedStart', null=True)),
                ('estimatedduration', models.IntegerField(blank=True, db_column='estimatedDuration', null=True)),
                ('actualstart', models.DateField(blank=True, db_column='actualStart', null=True)),
                ('actualduration', models.IntegerField(blank=True, db_column='actualDuration', null=True)),
                ('nexttaskid', models.BigIntegerField(blank=True, db_column='nextTaskId', null=True)),
                ('previoustaskid', models.BigIntegerField(blank=True, db_column='previousTaskId', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Task',
            },
        ),
        migrations.CreateModel(
            name='TaskLinksLabel',
            fields=[
                ('tasklinkslabelid', models.AutoField(db_column='tasklinkslabelid', primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tasklinkslabel',
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('taskstatusid', models.AutoField(db_column='taskStatusid', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'TaskStatus',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Userstory',
            fields=[
                ('userstoryid', models.AutoField(db_column='userstoryid', primary_key=True, serialize=False)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('createby', models.CharField(max_length=100)),
                ('createdate', models.DateField(blank=True, db_column='createDate', default=datetime.date.today, null=True)),
                ('updateby', models.CharField(max_length=100)),
                ('updatedate', models.DateField(blank=True, db_column='updatedate', default=datetime.date.today, null=True)),
            ],
            options={
                'managed': False,
                'ordering': ['-userstoryid'],
                'db_table': 'userstory',
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('worklogid', models.AutoField(db_column='workLogid', primary_key=True, serialize=False)),
                ('starttime', models.CharField(blank=True, db_column='startTime', max_length=100, null=True)),
                ('endtime', models.CharField(blank=True, db_column='endTime', max_length=100, null=True)),
                ('duration', models.CharField(blank=True, db_column='Duration', max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'WorkLog',
            },
        ),
        migrations.CreateModel(
            name='TeamResource',
            fields=[
                ('resourceid', models.ForeignKey(db_column='resourceid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, to='scrum.Resource')),
                ('teamid', models.ForeignKey(db_column='teamid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='scrum.Team')),
            ],
            options={
                'managed': False,
                'db_table': 'sprint',
            },
        ),
    ]
