# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_auto_20170502_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioReleases',
            fields=[
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('releaseid', models.AutoField(db_column='releaseid', primary_key=True, serialize=False)),
                ('planstartdate', models.DateField(blank=True, db_column='planstartdate', null=True)),
                ('actualstartdate', models.DateField(blank=True, db_column='actualstartdate', null=True)),
                ('planenddate', models.DateField(blank=True, db_column='planenddate', null=True)),
                ('actualenddate', models.DateField(blank=True, db_column='actualenddate', null=True)),
            ],
            options={
                'db_table': 'portfolioReleases',
                'managed': False,
            },
        ),
    ]
