# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0004_auto_20170510_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userstory',
            options={'managed': False, 'ordering': ['-userstoryid']},
        ),
        migrations.AlterModelTable(
            name='teamresource',
            table='sprint',
        ),
    ]
