# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0005_auto_20170528_1141'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sprint',
            table=None,
        ),
    ]
